# Generated by Django 3.2.7 on 2021-10-29 14:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(default=None, max_length=300)),
                ('absence_from', models.DateField()),
                ('absence_to', models.DateField()),
                ('approved', models.BooleanField(default=None)),
                ('approved_at', models.DateTimeField(default=datetime.datetime.now)),
                ('approved_by_comment', models.CharField(default=None, max_length=300)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absence_approver', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absence_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
