# Generated by Django 3.2.7 on 2021-10-29 13:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timenow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextended',
            name='comment',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='userextended',
            name='date_changed',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='userextended',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='userextended',
            name='date_deleted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='userextended',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserRepresent',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('date_changed', models.DateTimeField(default=datetime.datetime.now)),
                ('date_deleted', models.DateTimeField()),
                ('id_represent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userrepresent_represent', to=settings.AUTH_USER_MODEL)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userrepresent_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserContract',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('weekly_working_hours', models.IntegerField()),
                ('vacation_days', models.IntegerField()),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('date_changed', models.DateTimeField(default=datetime.datetime.now)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
