# Generated by Django 3.2.7 on 2021-10-29 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timenow', '0002_auto_20211029_1542'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
