# Generated by Django 3.2.7 on 2021-10-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timenow', '0003_delete_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextended',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
