# Generated by Django 3.2.7 on 2021-10-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timenow', '0005_alter_usercontract_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercontract',
            old_name='id_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userrepresent',
            old_name='id_represent',
            new_name='represent',
        ),
        migrations.RenameField(
            model_name='userrepresent',
            old_name='id_user',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='userrepresent',
            name='date_deleted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='userrepresent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
